FROM outstand/ruby-base:2.5.3-alpine
LABEL maintainer="Ryan Schlesinger <ryan@outstand.com>"

RUN addgroup stockpile && \
    adduser -S -G stockpile stockpile

ENV CONSUL_STOCKPILE_VERSION=0.1.5

RUN apk --no-cache add --virtual build-dependencies build-base && \
    gem install consul_stockpile -v ${CONSUL_STOCKPILE_VERSION} && \
    apk del build-dependencies

COPY scripts/docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/sbin/tini", "-g", "--", "/docker-entrypoint.sh"]
CMD ["help"]
